// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// log_pTB
double log_pTB(double k, double Km, double pi);
RcppExport SEXP _DSDM3_log_pTB(SEXP kSEXP, SEXP KmSEXP, SEXP piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type Km(KmSEXP);
    Rcpp::traits::input_parameter< double >::type pi(piSEXP);
    rcpp_result_gen = Rcpp::wrap(log_pTB(k, Km, pi));
    return rcpp_result_gen;
END_RCPP
}
// mod_fixed
void mod_fixed(arma::vec& c_init, arma::mat& xi_init, const arma::mat z, const arma::mat zero_loc, const unsigned int Km, const arma::vec log_pK, const arma::vec Mean_vec, const double s2_prior, const double a_ar, const double b_ar, const double s2_MH_xi, const double gm, const unsigned int iter, const double thin, arma::mat& c_mat, arma::vec& Kp_vec, arma::vec& K_vec, arma::mat& eta_mat, arma::cube& xi_cube, arma::cube& ar_cube, arma::vec& s2a_perform, arma::vec& s2a_accept);
RcppExport SEXP _DSDM3_mod_fixed(SEXP c_initSEXP, SEXP xi_initSEXP, SEXP zSEXP, SEXP zero_locSEXP, SEXP KmSEXP, SEXP log_pKSEXP, SEXP Mean_vecSEXP, SEXP s2_priorSEXP, SEXP a_arSEXP, SEXP b_arSEXP, SEXP s2_MH_xiSEXP, SEXP gmSEXP, SEXP iterSEXP, SEXP thinSEXP, SEXP c_matSEXP, SEXP Kp_vecSEXP, SEXP K_vecSEXP, SEXP eta_matSEXP, SEXP xi_cubeSEXP, SEXP ar_cubeSEXP, SEXP s2a_performSEXP, SEXP s2a_acceptSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type c_init(c_initSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type xi_init(xi_initSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type zero_loc(zero_locSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type Km(KmSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type log_pK(log_pKSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type Mean_vec(Mean_vecSEXP);
    Rcpp::traits::input_parameter< const double >::type s2_prior(s2_priorSEXP);
    Rcpp::traits::input_parameter< const double >::type a_ar(a_arSEXP);
    Rcpp::traits::input_parameter< const double >::type b_ar(b_arSEXP);
    Rcpp::traits::input_parameter< const double >::type s2_MH_xi(s2_MH_xiSEXP);
    Rcpp::traits::input_parameter< const double >::type gm(gmSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const double >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type c_mat(c_matSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type Kp_vec(Kp_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type K_vec(K_vecSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type eta_mat(eta_matSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type xi_cube(xi_cubeSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type ar_cube(ar_cubeSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type s2a_perform(s2a_performSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type s2a_accept(s2a_acceptSEXP);
    mod_fixed(c_init, xi_init, z, zero_loc, Km, log_pK, Mean_vec, s2_prior, a_ar, b_ar, s2_MH_xi, gm, iter, thin, c_mat, Kp_vec, K_vec, eta_mat, xi_cube, ar_cube, s2a_perform, s2a_accept);
    return R_NilValue;
END_RCPP
}
// logmar_data_DM
double logmar_data_DM(const arma::rowvec zi, const arma::rowvec xi_k);
RcppExport SEXP _DSDM3_logmar_data_DM(SEXP ziSEXP, SEXP xi_kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec >::type zi(ziSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type xi_k(xi_kSEXP);
    rcpp_result_gen = Rcpp::wrap(logmar_data_DM(zi, xi_k));
    return rcpp_result_gen;
END_RCPP
}
// logmar_data
double logmar_data(const arma::rowvec zi, const arma::rowvec at_risk_i, const arma::rowvec xi_k);
RcppExport SEXP _DSDM3_logmar_data(SEXP ziSEXP, SEXP at_risk_iSEXP, SEXP xi_kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec >::type zi(ziSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type at_risk_i(at_risk_iSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type xi_k(xi_kSEXP);
    rcpp_result_gen = Rcpp::wrap(logmar_data(zi, at_risk_i, xi_k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DSDM3_log_pTB", (DL_FUNC) &_DSDM3_log_pTB, 3},
    {"_DSDM3_mod_fixed", (DL_FUNC) &_DSDM3_mod_fixed, 22},
    {"_DSDM3_logmar_data_DM", (DL_FUNC) &_DSDM3_logmar_data_DM, 2},
    {"_DSDM3_logmar_data", (DL_FUNC) &_DSDM3_logmar_data, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_DSDM3(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
