# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmultinom_1 <- function(probs_arma) {
    .Call(`_DSDM3_rmultinom_1`, probs_arma)
}

log_sum_exp <- function(log_unnorm_prob) {
    .Call(`_DSDM3_log_sum_exp`, log_unnorm_prob)
}

log_marginal <- function(zi, gmi, beta_k) {
    .Call(`_DSDM3_log_marginal`, zi, gmi, beta_k)
}

logmar_ik <- function(zi, atrisk_i, beta_k) {
    .Call(`_DSDM3_logmar_ik`, zi, atrisk_i, beta_k)
}

logmar_k <- function(z, atrisk, beta_k) {
    .Call(`_DSDM3_logmar_k`, z, atrisk, beta_k)
}

logmar <- function(z, atrisk, beta_mat) {
    .Call(`_DSDM3_logmar`, z, atrisk, beta_mat)
}

log_atrisk <- function(zi, atrisk_i, beta_k, r0g, r1g) {
    .Call(`_DSDM3_log_atrisk`, zi, atrisk_i, beta_k, r0g, r1g)
}

launch_mcmc <- function(z, atrisk, beta_mat, ci_old, launch_iter, S, samp_clus, nk) {
    .Call(`_DSDM3_launch_mcmc`, z, atrisk, beta_mat, ci_old, launch_iter, S, samp_clus, nk)
}

log_proposal <- function(z, atrisk, beta_mat, ci_A, ci_B, S, samp_clus) {
    .Call(`_DSDM3_log_proposal`, z, atrisk, beta_mat, ci_A, ci_B, S, samp_clus)
}

split_beta <- function(nbeta, clus_split, clus_new, beta_old, mu, s2) {
    .Call(`_DSDM3_split_beta`, nbeta, clus_split, clus_new, beta_old, mu, s2)
}

update_atrisk <- function(z, atrisk_old, beta_mat, ci, r0g, r1g) {
    .Call(`_DSDM3_update_atrisk`, z, atrisk_old, beta_mat, ci, r0g, r1g)
}

update_beta <- function(z, atrisk, beta_old, ci, mu, s2, s2_MH) {
    .Call(`_DSDM3_update_beta`, z, atrisk, beta_old, ci, mu, s2, s2_MH)
}

update_beta_adaptive <- function(t, t_threshold, z, atrisk, beta_record, beta_init, ci, mu, s2, s2_MH) {
    .Call(`_DSDM3_update_beta_adaptive`, t, t_threshold, z, atrisk, beta_record, beta_init, ci, mu, s2, s2_MH)
}

realloc_full <- function(Kmax, z, atrisk, beta_mat, ci_old, theta) {
    .Call(`_DSDM3_realloc_full`, Kmax, z, atrisk, beta_mat, ci_old, theta)
}

sm <- function(Kmax, nbeta_split, z, atrisk, beta_old, ci_old, theta, mu, s2, launch_iter, r0c, r1c) {
    .Call(`_DSDM3_sm`, Kmax, nbeta_split, z, atrisk, beta_old, ci_old, theta, mu, s2, launch_iter, r0c, r1c)
}

mod <- function(iter, Kmax, nbeta_split, z, atrisk_init, beta_init, ci_init, theta, mu, s2, s2_MH, launch_iter, r0g, r1g, r0c, r1c, thin) {
    .Call(`_DSDM3_mod`, iter, Kmax, nbeta_split, z, atrisk_init, beta_init, ci_init, theta, mu, s2, s2_MH, launch_iter, r0g, r1g, r0c, r1c, thin)
}

mod_adaptive <- function(iter, Kmax, nbeta_split, z, atrisk_init, beta_init, ci_init, theta, mu, s2, s2_MH, t_thres, launch_iter, r0g, r1g, r0c, r1c, thin) {
    .Call(`_DSDM3_mod_adaptive`, iter, Kmax, nbeta_split, z, atrisk_init, beta_init, ci_init, theta, mu, s2, s2_MH, t_thres, launch_iter, r0g, r1g, r0c, r1c, thin)
}

realloc_dm <- function(Kmax, z, atrisk, beta_mat, ci_old, theta) {
    .Call(`_DSDM3_realloc_dm`, Kmax, z, atrisk, beta_mat, ci_old, theta)
}

DM_DM <- function(iter, Kmax, z, beta_init, ci_init, theta, mu, s2, s2_MH, t_thres, thin) {
    .Call(`_DSDM3_DM_DM`, iter, Kmax, z, beta_init, ci_init, theta, mu, s2, s2_MH, t_thres, thin)
}

DM_ZIDM <- function(iter, Kmax, nbeta_split, z, beta_init, ci_init, theta, mu, s2, s2_MH, t_thres, launch_iter, r0c, r1c, thin) {
    .Call(`_DSDM3_DM_ZIDM`, iter, Kmax, nbeta_split, z, beta_init, ci_init, theta, mu, s2, s2_MH, t_thres, launch_iter, r0c, r1c, thin)
}

ZIDM_DM <- function(iter, Kmax, z, atrisk_init, beta_init, ci_init, theta, mu, s2, s2_MH, t_thres, r0g, r1g, thin) {
    .Call(`_DSDM3_ZIDM_DM`, iter, Kmax, z, atrisk_init, beta_init, ci_init, theta, mu, s2, s2_MH, t_thres, r0g, r1g, thin)
}

