# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_pTB <- function(k, Km, pi) {
    .Call(`_DSDM3_log_pTB`, k, Km, pi)
}

mod_fixed <- function(c_init, xi_init, z, zero_loc, Km, log_pK, Mean_vec, s2_prior, a_ar, b_ar, s2_MH_xi, gm, iter, thin, c_mat, Kp_vec, K_vec, eta_mat, xi_cube, ar_cube, s2a_perform, s2a_accept) {
    invisible(.Call(`_DSDM3_mod_fixed`, c_init, xi_init, z, zero_loc, Km, log_pK, Mean_vec, s2_prior, a_ar, b_ar, s2_MH_xi, gm, iter, thin, c_mat, Kp_vec, K_vec, eta_mat, xi_cube, ar_cube, s2a_perform, s2a_accept))
}

logmar_data_DM <- function(zi, xi_k) {
    .Call(`_DSDM3_logmar_data_DM`, zi, xi_k)
}

logmar_data <- function(zi, at_risk_i, xi_k) {
    .Call(`_DSDM3_logmar_data`, zi, at_risk_i, xi_k)
}

